### ISSUE TITLE
docker-registry-ui container restarting. panic: yaml: line 83: did not find expected key

### ISSUE THREAD

**Issue by fti-sfuke** [Quiq/registry-ui#74]
**Issue:**
Encountered a panic error in Docker Registry UI, specifically: "yaml: line 83: did not find expected key". 

**Steps Taken:**

1. **Pull Image**: Pulled `quiq/docker-registry-ui:0.9.2` image successfully.

2. **Run Docker Container**: Executed the container with the following command:

    ```
    docker container run --detach --restart=always --network host \
    --volume /opt/scorer/etc/registry-ui/config.yml:/opt/config.yml:ro \
    --volume /opt/scorer/lib/mkcert/.ca/rootCA.pem:/etc/ssl/certs/ca-certificates.crt:ro \
    --volume /opt/scorer/lib/registry_ui:/opt/data:rw \
    --name ecr_registry_ui quiq/docker-registry-ui:0.9.2 -log-level=warn
    ```

3. *Successfully pulled the image*
```
Unable to find image 'quiq/docker-registry-ui:0.9.2' locally
0.9.2: Pulling from quiq/docker-registry-ui
df20fa9351a1: Pull complete 
f6055706147d: Pull complete 
5a88b35edf20: Pull complete 
dbc6941eb5d6: Pull complete 
8af3aa088aeb: Pull complete 
Digest: sha256:dd3087d83abc570c0115a3198e960d54296744806360753d86739823a87bf7b5
Status: Downloaded newer image for quiq/docker-registry-ui:0.9.2
52fa13978095182bda83721c0a1e9c859ce357d510211622a5a1cb5d370a432d
```
3. **Check Container Status**: Noticed the `docker-registry-ui` container repeatedly restarting.

    ```
    # docker ps -a | grep registry 

    52fa13978095   quiq/docker-registry-ui:0.9.2   "/opt/docker-registr…"   5 seconds ago   Restarting (2) 1 second ago   ecr_registry_ui
    358ba07b4b9d   registry:2   "/entrypoint.sh /etc…"   17 seconds ago   Up 16 seconds   ecr_registry
    ```

4. **Inspect Container Logs**: Examined the logs for the `ecr_registry_ui` container and found repeated occurrences of the panic error referencing line 83 in `main.go`.
```
root@DEB-NUC10i5F-G6FN04300231:~# docker logs ecr_registry_ui
panic: yaml: line 83: did not find expected key

goroutine 1 [running]:
main.main()
	/opt/src/main.go:83 +0x1886
panic: yaml: line 83: did not find expected key

goroutine 1 [running]:
main.main()
	/opt/src/main.go:83 +0x1886
panic: yaml: line 83: did not find expected key

goroutine 1 [running]:
main.main()
	/opt/src/main.go:83 +0x1886
panic: yaml: line 83: did not find expected key

goroutine 1 [running]:
main.main()
	/opt/src/main.go:83 +0x1886
panic: yaml: line 83: did not find expected key

goroutine 1 [running]:
main.main()
	/opt/src/main.go:83 +0x1886
panic: yaml: line 83: did not find expected key

goroutine 1 [running]:
main.main()
	/opt/src/main.go:83 +0x1886
panic: yaml: line 83: did not find expected key

goroutine 1 [running]:
main.main()
	/opt/src/main.go:83 +0x1886
panic: yaml: line 83: did not find expected key

goroutine 1 [running]:
main.main()
	/opt/src/main.go:83 +0x1886
panic: yaml: line 83: did not find expected key

goroutine 1 [running]:
main.main()
	/opt/src/main.go:83 +0x1886

```

**Environment :** 
```
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@DEB-NUC10i5F-G6FN04300231:~/chetan/scorer/Manufacturing/debian/scripts# 
```

**Comment by roman-vynar** [comment]
Please use the latest version 0.10.0, not the one from 2020.

**Comment by fti-sfuke** [comment]
@roman-vynar San,
The config.yml file in the master branch and the latest 0.10.0 version isn't working for me it's causing a YAML panic error.
https://github.com/Quiq/registry-ui/blob/master/config.yml
https://github.com/Quiq/registry-ui/blob/0.10.0/config.yml

When I use the tag-specific config.yml file instead of the one from the master branch, it works well for versions like 0.9.7 to 0.9.2. However, the config.yml from the master branch leads to a panic error in YAML parsing, as mentioned earlier: https://github.com/Quiq/registry-ui/issues/74#issue-2248164307

Replacing it with the tag-specific one resolves the issue. 
https://github.com/Quiq/registry-ui/blob/0.9.7/config.yml
raw.githubusercontent.com/Quiq/registry-ui/0.9.7/config.yml

Could you please confirm why the master branch config.yml is causing this error?

**Successfully hosted Docker Registry UI now.**

```
# docker container run --detach --restart=always --network host \
--volume /opt/scorer/etc/registry-ui/config.yml:/opt/config.yml:ro \
--volume /opt/scorer/lib/mkcert/.ca/rootCA.pem:/etc/ssl/certs/ca-certificates.crt:ro \
--volume /opt/scorer/lib/registry_ui:/opt/data:rw \
--name ecr_registry_ui quiq/docker-registry-ui:0.9.2 -log-level=warn
----------------------------------------
daa69dce627b397c68fe682de31fcd6116c1506adad15d09749bbb3eab0c1a0b
----------------------------------------

# docker container ls --filter 'name=scorer_registry_ui$' | grep -w Up
----------------------------------------
daa69dce627b   quiq/docker-registry-ui:0.9.2   "/opt/docker-registr…"   5 seconds ago   Up 5 seconds    ecr_registry_ui
----------------------------------------

#4120-13 | wget -q --tries 10 --retry-connrefused -O -         http://127.0.0.1:9010/ |         grep -F '<title>Docker Registry UI</title>'
----------------------------------------
        <title>Docker Registry UI</title>
----------------------------------------

#4120-14 | wget -q --tries 10 --retry-connrefused -O -         http://DEB-NUC10i5F-G6FN04300231.local:9010/ |         grep -F '<title>Docker Registry UI</title>'
----------------------------------------
        <title>Docker Registry UI</title>
----------------------------------------

root@DEB-NUC10i5F-G6FN04300231:~# docker logs ecr_registry_ui
   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.1.16
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on [::]:9010
root@DEB-NUC10i5F-G6FN04300231:~
```
